name: Website Improvement
description: Suggest an improvement for the Datastar website.
labels:
  - website
body:
  - type: markdown
    attributes:
      value: |
        So you’d like to help improve the Datastar website? Great!
        
        Please provide clear and concise suggestions for improvements to the website. This can include documentation, changes to existing content, or general usability enhancements.
  - type: textarea
    id: body
    attributes:
      label: Improvement Suggestion
      description: Please provide a clear and concise suggestion for an improvement to the site.
    validations:
      required: true
